Auth
Inno-Gang/room-booking pull request #12
Opened 2023-06-22 19:31 UTC by Tyu-cr

2023-06-27 17:32 UTC, evermake commented
@Tyu-cr, how things are going? Do you need some help?

2023-06-27 17:56 UTC, Tyu-cr commented
No. I will push all changes toworrow i guess. Almost done

2023-06-28 17:47 UTC, evermake commented
<img width="432" alt="image" src="https://github.com/Inno-Gang/room-booking/assets/53311479/520db2ff-1ee1-42ac-b86a-d8f993ec8053">

@Tyu-cr , have you installed `jwt` package with `pip`? We use `poetry` as the project's dependency manager.

2023-06-28 18:07 UTC, evermake requested changes

2023-06-28 18:07 UTC, evermake commented on app/api/deps.py
> +        if check_token_expired(access_token, "access"):
Please, read PyJWT documentation carefully. Especially [this](https://pyjwt.readthedocs.io/en/latest/usage.html#expiration-time-claim-exp). Why reinvent the wheel?

2023-06-28 18:07 UTC, evermake commented on app/api/iam/router.py
> +    refresh_token = create_jwt_token(
Refresh tokens should not be JWT tokens. It's just a secure randomly generated string, that should be stored in the system. Please, read the issue #8 , where I described everything and ask me, if something is unclear.

2023-06-28 18:07 UTC, evermake commented on app/api/iam/schemas.py
> +class UserPassword(User):
1. Why separate model?
2. Users will not have passwords 🙁

2023-06-28 18:07 UTC, evermake commented on app/api/iam/utils.py
> +test_db = {
I think you wanted to implement an `AuthRepository` in `app.adapters`, but not put it there...

2023-06-28 18:07 UTC, evermake commented on app/api/iam/utils.py
> +        # current_time = datetime.utcnow().timestamp()
Uncomment or remove code

2023-06-28 18:18 UTC, Tyu-cr commented on app/api/iam/router.py
> +    refresh_token = create_jwt_token(
What is the difference? jwt is basically the same thing, but with additional checks.

2023-06-28 18:18 UTC, Tyu-cr commented on app/api/iam/utils.py
> +test_db = {
Maybe, I'll ask you about it later.

2023-06-28 18:19 UTC, Tyu-cr commented on app/api/iam/schemas.py
> +class UserPassword(User):
2. How did they login tho, only email?🤨

2023-06-28 18:20 UTC, Tyu-cr commented on app/config.py
> +    # TODO: encode keys in base64
Some stack overflow guys say it's even better. idk

2023-06-28 18:44 UTC, evermake commented on app/api/iam/schemas.py
> +class UserPassword(User):
Read the issue #8 carefully again

2023-06-28 18:47 UTC, evermake commented on app/api/iam/router.py
> +    refresh_token = create_jwt_token(
JWT tokens are meant to hold some information and not to be stored on backend.

We don't need to hold any information, we just need a long random string, which is stored on backend.

2023-06-28 18:48 UTC, evermake commented on app/config.py
> +    # TODO: encode keys in base64
It's okay to use one generated by `openssl rand -hex 32`

2023-06-28 19:01 UTC, Tyu-cr commented on app/api/iam/router.py
> +    refresh_token = create_jwt_token(
Expiration time?

2023-06-28 19:02 UTC, Tyu-cr commented on app/api/iam/schemas.py
> +class UserPassword(User):
oke

2023-07-10 18:06 UTC, evermake approved these changes

2023-07-10 18:06 UTC, merged