Outlook adapter implementation
Inno-Gang/room-booking pull request #13
Opened 2023-06-23 16:54 UTC by metafates

2023-06-27 17:49 UTC, evermake requested changes

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +class _Rooms:
No need for `_`

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +class Adapter(BookingsRepo):
Rename to `OutlookAdapter`

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +    _name = str
Remove this, just use `str`, it only confuses

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +class Config(TypedDict):
Rename to `OutlookAdapterDict`

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +        if (location := item.location) is not None:
Do not use EWS `Location` element for identifying room. It can be any string and even if it is a valid room name it means nothing, since user can type it manually.

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +        def room_to_account(room: Room) -> exchangelib.Account:
Rename to `get_ews_account_for_room`

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +            required_attendees=[
Why we add `primary_smtp_address` and `owner` as required attendees? And why owner should have `response_type` set to `Accept`?

2023-06-27 17:49 UTC, evermake commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
I don't like the "sometimes index 1, sometimes index 0". There should be a deterministic way to get the actual owner. For example, check the [`Attendee`](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/attendee)'s `ResponseType` element — according to documentation it can be `Organizer`, if it is always so, definitely its better to find the organizer in a list, than hoping that index will be correct.

2023-06-27 22:42 UTC, metafates commented on app/adapters/outlook.py
> +class _Rooms:
But `_Room` is supposed to be a file private - it has no use on it's own outside of this file. Are there better ways to achieve this?

2023-06-27 22:42 UTC, metafates commented on app/adapters/outlook.py
> +class _Rooms:
> No need for `_`

But `_Room` is supposed to be a file private - it has no use on it's own outside of this file. Are there better ways to achieve this?

2023-06-27 22:49 UTC, metafates commented on app/adapters/outlook.py
> +class Adapter(BookingsRepo):
> Rename to `OutlookAdapter`

Do we need to duplicate module name twice? File is already named `outlook.py` so when we import this adapter 

```python
from adapters import outlook

outlook.Adapter()
```

IMO looks cleaner than

```python
from adapters import outlook

outlook.OutlookAdapter()
```

Going further...

```python
import entities

entities.booking.BookingBooking()
entities.booking.BookingRoom()
```

2023-06-27 22:56 UTC, metafates commented on app/adapters/outlook.py
> +        if (location := item.location) is not None:
It's used as a last resort before raising an exception. I don't see why it shouldn't be considered since it's being set by the current system internally. If it's used, then it means that user somehow also manually typed `required_attendees` and `resources` which isn't possible I believe?

```php
$event->Location = $room_booking->room->name_en . ' (' . $room_booking->organizer_email . ')';

```

2023-06-27 23:10 UTC, metafates commented on app/adapters/outlook.py
> +from app.domain.entities.common import Language
I think we need a linter on CI for it then

2023-06-28 07:12 UTC, evermake commented on app/adapters/outlook.py
> +class _Rooms:
You can remove `_`, create the [`__all__`](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) list, and include only "exported" module members.

2023-06-28 07:14 UTC, evermake commented on app/adapters/outlook.py
> +from app.domain.entities.common import Language
Ok, created an issue #19

2023-06-28 07:19 UTC, evermake commented on app/adapters/outlook.py
> +        if (location := item.location) is not None:
I can create an event with any content in this field like this:

<img width="549" alt="image" src="https://github.com/Inno-Gang/room-booking/assets/53311479/59bcccd7-b7c2-459c-b459-853b03b5211e">

Here I specified room's name, though I didn't actually book it. We should ignore location field and try to find a better way.

Btw, maybe it was set manually as I showed in your "at least one observed case".

2023-06-28 07:21 UTC, evermake commented on app/adapters/outlook.py
> +class Adapter(BookingsRepo):
Okay, then rename to `BookingsRepoAdapter`. Because name `Adapter` doesn't give an idea of what kind of adapter it is.

2023-06-28 09:05 UTC, metafates commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
So, first, try to find the owner by response type, if it fails, use this guess? The problem is that `Organizer` is never set properly

Take this example:

```python
for item in a.calendar.all():
    for a in item.required_attendees:
        print(a.response_type)
```

outputs:

```
Unknown
Unknown
Unknown
Unknown
Accept
Unknown
Unknown
Accept
Unknown
Unknown
Accept
Unknown
```

The same goes for the current system, which doesn't use `Organizer` at all

2023-06-28 09:33 UTC, evermake commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
In this case the owner of a booking is unknown for us; and we should return `None`. Using hard-coded indexing can result in runtime error in any moment.

In which environment and from which account did you do this request? Maybe it's hidden, if you're making request from the personal account that doesn't have enough rights.

2023-06-28 09:43 UTC, metafates commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
> In which environment and from which account did you do this request?

From my personal account and from the sandboxed one (that we were given)

2023-06-28 10:05 UTC, evermake commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
How this will help, if an event is created by someone other than us?

2023-06-28 10:09 UTC, metafates commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
I thought we needed to be compatible with the current system, so that it will be integrated more easily in the current university workflow

2023-06-28 14:30 UTC, metafates commented on app/adapters/outlook.py
> +        return self._rooms_by_name_map.get(name)
I think this class should be moved to a separate file/module

2023-06-28 15:01 UTC, evermake commented on app/adapters/outlook.py
> +        # We have to deal with two* cases here
You're right, but this (code above) will not save us in the case someone will book the room in "wrong" format. Uni staff still will be able to manually create events and our system must be ready for that.

2023-07-03 10:45 UTC, evermake requested changes

2023-07-03 10:45 UTC, evermake commented on app/adapters/outlook.py
> +    attendee = attendees[0]
Before accessing elements make sure that length is exactly 2 (is this how legacy room booking service registers bookings?)

2023-07-11 19:37 UTC, catdog905 approved these changes

2023-07-11 19:39 UTC, merged

2023-07-12 09:38 UTC, evermake commented
@catdog905 , we follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).