v0.1.0
Inno-Gang/room-booking pull request #7
Opened 2023-06-17 12:09 UTC by evermake

2023-06-17 13:58 UTC, ruca905 requested changes

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/schemas.py
> +        description="Owner of the booking. Can be omitted, if the request is made by the user who books a room.",
Не очень понимаю, что тут сказано в комментарии. Почему owner_email_address может быть None?

2023-06-17 13:58 UTC, ruca905 commented on app/api/app.py
> +from fastapi import FastAPI
К каждой ручке надо добавить 500 ошибку, которая будет падать по умолчанию
Ведь может Outlook API быть недоступным. Может быть проблемы с параллельными запросами. Может просто сервис упасть

2023-06-17 13:58 UTC, ruca905 commented on app/domain/use_cases.py
> +async def delete_booking_by_user(
Тут явно должно быть 403 ошибка, если пытаешься удалить чужое бронирование

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/router.py
> +        status.HTTP_400_BAD_REQUEST: {
Может добавить ещё ошибки о превышении лимита бронирования одним человеком

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/router.py
> +@router.get("/bookings/my")
Этого нет в схеме, что Влад скинул

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/router.py
> +async def query_bookings(req: QueryBookingsRequest) -> list[Booking]:
Давай здесь возвращать пользователю email человека, который забронировал комнату. Это бывает полезно

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/router.py
> +async def delete_booking(booking_id: str) -> None:
Тут я думаю не должно быть возвращаемого значения, в swagger editor это выглядит как будто у ответа есть тело

2023-06-17 13:58 UTC, ruca905 commented on app/api/booking/router.py
> +async def query_bookings(req: QueryBookingsRequest) -> list[Booking]:
Не хочешь также пагинации добавить? Бронирований то, много может быть, если не указать фильтр

2023-06-17 14:08 UTC, evermake commented on app/api/booking/schemas.py
> +        description="Owner of the booking. Can be omitted, if the request is made by the user who books a room.",
Если запрос от тебя, мы можем понять, кто бронирует. Ещё может Telegram бот делать запрос, тогда он должен указать, кому он бронирует.

2023-06-17 14:09 UTC, evermake commented on app/domain/use_cases.py
> +async def delete_booking_by_user(
Человек не должен в теории знать о чужих, тогда 404. Хотя если мы список всех броней возвращаем, то тогда наверное да.

2023-06-17 14:09 UTC, evermake commented on app/api/booking/router.py
> +        status.HTTP_400_BAD_REQUEST: {
Там очень много причин может быть, пока одной ошибкой это всё будет.

2023-06-17 14:10 UTC, evermake commented on app/api/booking/router.py
> +@router.get("/bookings/my")
Закомментил, когда отправлял Андрею, потому что для запросов от бота это неактуально.

2023-06-17 14:12 UTC, evermake commented on app/api/booking/router.py
> +async def query_bookings(req: QueryBookingsRequest) -> list[Booking]:
1. В Booking думаю включить владельца брони, но тогда любой человек сможет получить все брони любого другого человека, думаю нужно ли с этим что-то делать, и если да, то что.

2. Безусловно надо что-то такое, пока не придумал, как лучше сделать.

2023-06-17 14:13 UTC, evermake commented on app/api/booking/router.py
> +async def delete_booking(booking_id: str) -> None:
Если явно не писать → None, Python сам это делает. В Swagger не в этом проблема, но можно разобраться

2023-06-17 14:14 UTC, evermake commented on app/api/app.py
> +from fastapi import FastAPI
Много чего надо, это пока драфт :)

2023-06-17 14:14 UTC, evermake commented on app/api/booking/schemas.py
> +    id: str
А если нет перевода на локаль пользователя, то что возвращать?

2023-06-17 15:51 UTC, ruca905 commented on app/api/booking/schemas.py
> +    id: str
Соответствующую ошибку

2023-06-17 15:52 UTC, ruca905 commented on app/api/app.py
> +from fastapi import FastAPI
Ну, нам завтра же это Андрею показывать. А он это опубликует вроде

2023-06-17 15:54 UTC, ruca905 commented on app/domain/use_cases.py
> +async def delete_booking_by_user(
Ну, насколько я понимаю, идеологически мы в принципе на все коды, кроме своих должны 403 кидать. Но тут, конечно, политика. Ни на что это особо и не влияет. Главное, чтобы хоть что то было

2023-06-17 15:58 UTC, ruca905 commented on app/api/booking/router.py
> +async def query_bookings(req: QueryBookingsRequest) -> list[Booking]:
1. Тут это, я думаю, относительно открытая информация. Не уверен, что это надо прятать
2. В запросе передавать limit, offset необязательными параметрами, которые имеют значение по умолчанию, а возвращать новый offset и кол-во записей в выборке в принципе

2023-06-17 16:07 UTC, evermake commented on app/api/booking/schemas.py
> +    id: str
То есть человек хотел узнать номер комнаты, а мы возвращаем ошибку, что ещё не перевели на его язык название комнаты?

2023-06-17 16:08 UTC, evermake commented on app/api/app.py
> +from fastapi import FastAPI
500-ю ошибку и так всегда ожидать надо :)

2023-06-17 16:20 UTC, evermake commented on app/api/booking/schemas.py
> +    id: str
На [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) пишут:

> The server possibly can send back a [406](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) (Not Acceptable) error code when unable to serve content in a matching language. However, such a behavior is rarely implemented for a better user experience, and servers often ignore the Accept-Language header in such cases.

2023-06-17 18:43 UTC, evermake commented on app/api/booking/router.py
> +async def query_bookings(req: QueryBookingsRequest) -> list[Booking]:
2. добавлю issue, потом сделаем

2023-06-17 18:43 UTC, evermake commented on app/domain/use_cases.py
> +async def delete_booking_by_user(
Когда реализовывать будем, подправим если что

2023-06-17 20:09 UTC, ruca905 commented on app/api/deps.py
> +            example="ru-RU",
Стрёмно, что в openapi схеме не генерирует default значение

2023-06-17 20:09 UTC, ruca905 commented on app/api/booking/router.py
> +    dependencies=[Depends(locale), Depends(auth)],
Либо у меня не последняя версия openapi файла, либо тут что-то не так. В post и delete запросах не передаётся токен в swagger

2023-06-18 07:42 UTC, evermake commented on app/api/deps.py
> +            example="ru-RU",
а эт чо?
<img width="498" alt="image" src="https://github.com/Inno-Gang/room-booking/assets/53311479/7e20b2fb-8c8a-4ed2-9cf9-8a1669d58d0b">

2023-06-18 07:45 UTC, evermake commented on app/api/booking/router.py
> +    dependencies=[Depends(locale), Depends(auth)],
Да, он не показывает header для авторизации, но там сделано через авторизацию. Сами OpenAPI рекомендуют так делать:

<img width="1175" alt="Screenshot 2023-06-18 at 10 44 11 AM" src="https://github.com/Inno-Gang/room-booking/assets/53311479/f6587685-f795-4ea2-9d91-915e2de87aea">

(Auth у меня локально пока только)

2023-06-18 08:13 UTC, ruca905 commented on app/api/deps.py
> +            example="ru-RU",
Это example

2023-06-18 08:15 UTC, ruca905 commented on app/api/booking/router.py
> +    dependencies=[Depends(locale), Depends(auth)],
Типо и api key и api token в один и тот же header передаётся? А, или api token пока что нет в этой версии

2023-06-18 08:15 UTC, ruca905 approved these changes

2023-06-18 08:15 UTC, evermake commented on app/api/booking/router.py
> +    dependencies=[Depends(locale), Depends(auth)],
в один header будут передаваться, да. Пока у нас ничего нет)

2023-06-18 08:16 UTC, evermake commented on app/api/deps.py
> +            example="ru-RU",
на 20 пикселей вверх прицелься :)

2023-06-18 08:31 UTC, merged